lib/login/ui/create_account_page.dart, lib/login/ui/recover_password.dart, lib/settings/ui/pages/change_pass/password_strength.dart
=> Fix password strength

lib/tools/ui/refresher.dart
Fix refresher clip effect when the child is not tall enough to fill the entire screen
*must be tested on ios*
=> Fix refresher

lib/cinema/providers/main_page_index_provider.dart, lib/cinema/providers/session_list_page_provider.dart, lib/cinema/ui/pages/main_page/main_page.dart
- cinema autoscroll to current date
=> Adding cinema feature

web/index.html, web/manifest.json
Update title and meta description to
=> Improve index.html for search engines

lib/drawer/ui/custom_drawer.dart, lib/drawer/ui/drawer_template.dart, lib/drawer/ui/notification_badge.dart, lib/drawer/ui/top_bar.dart, lib/home/ui/home.dart, lib/login/class/create_account.dart, lib/login/tools/constants.dart, lib/login/ui/create_account_page.dart, lib/login/ui/login_field.dart, lib/others/ui/email_change_popup.dart, lib/tools/constants.dart, lib/tools/functions.dart, lib/tools/providers/should_notify_provider.dart, lib/user/providers/user_provider.dart, lib/user/repositories/user_repository.dart, pubspec.lock, pubspec.yaml
Display a popup whenever the user email does not match the new email regex.
View of the popup
=> Forcing changing mail

lib/tools/ui/refresher.dart
Last update to Refresher did not correct web refresher
=> Add layout builder constraints for web app refresher

lib/vote/ui/pages/pretendance_pages/add_edit_pretendance.dart
Goal of this PR : Fix a bug that prevent web user from uploading image 
The reason was that web and app cases were handled the same way (the app one), which does not work for the web. 
The web case is now handled.
=> Fix: Image uploading : Handling web case

lib/tools/ui/dialog.dart
Goal of this PR : Fixing the onNobutton behavior. It was unstacking pages behind the dialog and disposing it. This is fixed by using the Widget context instead of the QR one
=> Fixing onNo button behavior

lib/login/tools/constants.dart
- fix regex dots which were not escaped
- allow centraliens-lyon.net to sign up
=> Fix regex dots + allow centraliens-lyon.net

lib/admin/ui/pages/add_loaner_page/add_loaner_page.dart, lib/advert/ui/pages/form_page/add_rem_announcer_page.dart, lib/event/ui/pages/main_page/main_page.dart
Goal of this PR : Removes the blue color of some loader
- This PR will be useless when https://github.com/aeecleclair/Titan/pull/91 will be merged, it is a quick fix
=> Removing blue as loader color

lib/login/router.dart, lib/main.dart
which caused some page to have a grey background.
See https://pub.dev/packages/qlevar_router#page-transition
https://github.com/aeecleclair/Titan/assets/95971503/0e5f4f10-e8c9-4701-858d-65cb1a865ee8
https://github.com/aeecleclair/Titan/assets/95971503/53d780c3-6ef7-42c2-9f18-693a9236c1ae
=> fix page type to prevent a mix of QCupertinoPage and QMaterialPage

lib/booking/ui/booking_card.dart, lib/service/tools/setup.dart
Color of the booking card changed to green if the request is accepted and red if the request is declined.
=> Color change of booking card depending on decision

lib/advert/providers/announcer_provider.dart, lib/advert/repositories/announcer_repository.dart, lib/advert/ui/tools/announcer_bar.dart
fix a bug where the announcer bar would not update when multi select is on
=> fix advert announcer bar

lib/drawer/providers/display_notification_popup.dart, lib/drawer/ui/drawer_template.dart, lib/drawer/ui/notification_popup.dart, lib/service/providers/topic_provider.dart
Goal of this PR : Add a only once pop-up at first opening to allow user to select module to receive notification from.
Images (if the PR changes the front) :
| Mobile |
| ------ |
|![image](https://github.com/aeecleclair/Titan/assets/34400034/1e5c3094-9353-4c2d-a24e-7e1b8599ae9c)|
On first start
=> Adding first opening notification pop up

lib/home/router.dart, lib/home/ui/days_event.dart, lib/loan/ui/pages/admin_page/on_going_loan.dart
Fixes two router issues :
- Wrong page when editing loan
- Opening calendar event detail does not open the detail page
Solution for https://github.com/aeecleclair/Titan/issues/160
=> Fixing router

lib/event/tools/functions.dart
Solution for https://github.com/aeecleclair/Titan/issues/133
=> Adding condition to properly discriminate delay of date to today

lib/amap/ui/pages/presentation_page/text.dart, lib/centralisation/tools/functions.dart, lib/centralisation/ui/pages/main_page.dart, lib/tools/ui/text_with_hyper_link.dart
Goal of this PR : Enhance the UI of Centralisation
Other information :
- Response to https://github.com/aeecleclair/Titan/issues/152
=> Fixing Centralisation

lib/login/tools/constants.dart
Rename "Promo" to "Promo entrante (ex : 2023)" when register
=> Rename Promo hint

lib/login/tools/constants.dart
=> Change field name for promo in sign up process

lib/cinema/repositories/cinema_topic_repository.dart, lib/cinema/ui/pages/main_page/main_page.dart, lib/service/local_notification_service.dart
=> Fixing notifications

lib/service/tools/setup.dart
Fix background notifications by removing Firebase requestPermission on background notification handling
=> Fix background notifications

lib/cinema/ui/pages/detail_page/detail_page.dart, lib/cinema/ui/pages/main_page/session_card.dart, lib/service/local_notification_service.dart
Goal of this PR : Adding a temporary solution to have scheduled notification
=> fix: Adding temporary solution to handle timezone

lib/login/ui/create_account_page.dart, lib/login/ui/recover_password.dart
Goal of this PR : Resolve two login problems
=> Fixing-login

lib/drawer/providers/should_setup_provider.dart, lib/drawer/ui/drawer_template.dart, lib/service/tools/setup.dart
- fix register device boolean expression
- one condition is temporary and should be deleted after october 13th (this allows devices to register devices where FCM token has been created before september 12th)
=> Fix register device condition

lib/event/tools/functions.dart, lib/home/ui/home.dart
Goal of this PR : Fixes the function formatDelayToToday and UI
Solution for https://github.com/aeecleclair/Titan/issues/174
=> fix: updating formatDelayToToday

lib/booking/ui/pages/booking_pages/add_edit_booking_page.dart, lib/event/ui/pages/event_pages/add_edit_event_page.dart, lib/tools/functions.dart, pubspec.lock
Goal of this PR : Fixes a bug that prevent user to create event during a change of a month
=> fix: checking date instead of string

lib/settings/providers/module_list_provider.dart, lib/vote/class/voter.dart, lib/vote/providers/can_vote_provider.dart, lib/vote/providers/voter_list_provider.dart, lib/vote/providers/voting_group_list_provider.dart, lib/vote/repositories/voter_repository.dart, lib/vote/tools/constants.dart, lib/vote/ui/pages/admin_page/admin_page.dart, lib/vote/ui/pages/admin_page/voter_chip.dart, lib/vote/ui/pages/admin_page/voters_bar.dart, lib/vote/ui/pages/main_page/main_page.dart, lib/vote/ui/vote.dart
Adding possibility to selected group that can vote
=> Multi voter campaign

lib/service/tools/setup.dart
=> Remove temporary FCM device registration condition

.github/workflows/release-web.yml
Replace "+" in tag by "-" for docker registry
=> Fix registry tag

.github/workflows/release-web.yml, Dockerfile
- Fix app path in Dockerfile
- Fix web favicon (use .png instead of .ico)
=> Actions web fix

lib/login/ui/pages/create_account_page/create_account_page.dart
Goal of this PR : Forcing promo to be an int 
- Solves https://github.com/aeecleclair/Titan/issues/153
=> fix: forcing promo to be an int

lib/advert/ui/components/announcer_bar.dart, lib/tools/ui/layouts/item_chip.dart, lib/vote/ui/components/contender_logo.dart, lib/vote/ui/pages/admin_page/voter_chip.dart, lib/vote/ui/pages/main_page/main_page.dart
Fixing image to small to be displayed
Main page
Fixing chip at the same time
=> Fixing invisible section image

lib/admin/providers/is_expanded_list_provider.dart, lib/admin/ui/pages/edit_module_visibility/modules_expansion_panel.dart
Goal of this PR : 
- Fixing visibility expansion panel toggle
-  Solves https://github.com/aeecleclair/Titan/issues/217
=> Fixing visibility expansion panel toggle

lib/tools/functions.dart
Goal of this PR : Solves https://github.com/aeecleclair/Titan/issues/235
=> feat: using initial date before now date

lib/drawer/ui/list_module.dart
Close https://github.com/aeecleclair/Titan/issues/204
=> feat: adding persistent scrollbar

lib/event/ui/pages/event_pages/add_edit_event_page.dart, lib/event/ui/pages/main_page/main_page.dart
Goal of this PR : 
Solves #255 
Solves #254
=> fix : event recurrences and scrolling issues

lib/event/ui/pages/admin_page/list_event.dart
=> Change(Event): Make event approuvable until end date is paste

lib/booking/ui/components/booking_card.dart, lib/event/ui/components/event_ui.dart
=> Fix overflow on card infos

lib/event/tools/constants.dart, lib/event/ui/pages/admin_page/admin_page.dart, lib/event/ui/pages/admin_page/list_event.dart
Close #215 
And thus :
Close #203
=> feat:admins can now see paste events and change their decisions

lib/login/ui/pages/create_account_page/create_account_page.dart, lib/login/ui/pages/register_page/register_page.dart
=> Login: Fix register date picker

lib/admin/repositories/group_repository.dart, lib/vote/providers/can_vote_provider.dart
This fix will replace the retro compatible PR : https://github.com/aeecleclair/Hyperion/pull/307
=> fix(campaign): get groups allowed to vote for non admin

lib/loan/ui/pages/item_group_page/add_edit_item_page.dart
=> Fix(Loan): Possible duration as int

lib/raffle/router.dart
Or should we modify root on Hyperion ?
=> fix:update raffle root to match hyperion modules list

lib/amap/repositories/delivery_list_repository.dart
Close #285 
Also fix other requests using patch method instead of the post method required.
=> Fix(AMAP) : Fix Delevery List Repository

lib/amap/providers/cash_list_provider.dart, lib/amap/ui/pages/admin_page/user_cash_ui.dart
=> Fix(AMAP) : Fix cash provider update cash 

lib/admin/providers/section_logo_provider.dart, lib/admin/providers/simple_groups_groups_provider.dart, lib/advert/providers/advert_posters_provider.dart, lib/amap/providers/delivery_order_list_provider.dart, lib/cinema/providers/session_poster_map_provider.dart, lib/loan/providers/admin_history_loan_list_provider.dart, lib/loan/providers/admin_loan_list_provider.dart, lib/loan/providers/loaners_items_provider.dart, lib/raffle/providers/raffle_stats_map_provider.dart, lib/raffle/providers/tombola_logos_provider.dart, lib/tools/providers/map_provider.dart, lib/tools/ui/builders/auto_loader_child.dart, lib/vote/providers/contender_logos_provider.dart, lib/vote/providers/sections_contender_provider.dart, lib/vote/providers/sections_stats_provider.dart, test/tools/providers/map_notifier_test.dart
=> feat: adding no data state

lib/advert/ui/components/advert_card.dart
=> Fix(Advert): Overflow in web advert page

.github/workflows/build.yml, .github/workflows/release-mobile.yml, .github/workflows/release-web.yml, android/app/build.gradle, android/build.gradle, android/settings.gradle, pubspec.lock
See https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
=> Migrate graddle apply script method

lib/booking/ui/calendar/calendar_dialog.dart, lib/booking/ui/calendar/calendar_dialog_button.dart
=> Fix overflow on admin calendar pop up

.github/workflows/build.yml, .github/workflows/release-mobile.yml, .github/workflows/release-web.yml, pubspec.yaml
New pre release to fix the web (see #331)
=> Pre release

lib/loan/class/item.dart, lib/loan/providers/end_provider.dart, lib/loan/ui/pages/item_group_page/add_edit_item_page.dart, test/loan/loan_test.dart
=> Fix Loan Item List

lib/drawer/ui/notification_popup.dart
In order to fix the overflow in notificaton popup :
=> Notification popup

lib/ph/ui/pages/past_ph_selection_page/ph_card.dart
In order to fix overflow in PH card :
=> PH card ui

lib/ph/ui/pages/main_page/main_page.dart
The PH on main page is now the last one
=> Fix last PH on main page

lib/ph/tools/constants.dart, lib/ph/ui/pages/admin_page/admin_ph_card.dart, lib/ph/ui/pages/past_ph_selection_page/ph_card.dart, lib/ph/ui/pages/past_ph_selection_page/ph_list.dart, lib/tools/ui/layouts/card_button.dart, lib/tools/ui/layouts/card_layout.dart
=> Update on past ph page

lib/phonebook/ui/pages/association_page/member_card.dart, lib/phonebook/ui/pages/association_page/web_member_card.dart
Attempt to fix #424 and #430 at once
=> Phonebook member cards : left-aligning on mobile, adding profile pictures on web

lib/purchases/ui/pages/main_page/main_page.dart, lib/purchases/ui/pages/scan_page/scan_dialog.dart, lib/purchases/ui/pages/scan_page/scan_page.dart, lib/purchases/ui/pages/scan_page/ticket_card.dart, lib/purchases/ui/pages/user_list_page/user_list_page.dart
Goal of this PR : 
Required unmerged PR :
Images (if the PR changes the front) :
| Desktop | Mobile |
| ------- | ------ |
|         |        |
-
=> fix: adding missing tokenExpireWrapper

lib/booking/tools/constants.dart, lib/booking/ui/components/booking_card.dart
=> Replaced keys with keys requested

lib/flappybird/ui/pages/game_page/pipe.dart
Fix the pipes from the flappy bird game.
=> Fix lighting consistency

pubspec.yaml
Downgrade mobile_scanner to 0.6.2
=> fix: working mobile scanner

lib/paiement/ui/components/transaction_card.dart
Dates in French.
Screenshot to save you some time:
=> Fix: date locale

lib/paiement/providers/has_accepted_tos_provider.dart, lib/paiement/ui/pages/devices_page/devices_page.dart, lib/paiement/ui/pages/main_page/account_card/account_card.dart, lib/paiement/ui/pages/main_page/main_page.dart, lib/paiement/ui/pages/store_admin_page/search_result.dart
Requires https://github.com/aeecleclair/Hyperion/pull/738
If you refuse the last ToS you
* keep full read access: balance, history, stats, and devices)
* lose all write access: funding, buying, managing devices
This is for the buyer part. The seller part is unaffected
=> Allow read access even when last ToS are refused

lib/centralisation/class/section.dart, lib/centralisation/repositories/section_repository.dart
Just the compiler unhappy of casting types too early
=> Fix: Centralisation JSON dynamic parsing
