aeecleclair/Titan

- lib/amap/router.dart
- lib/booking/router.dart
- lib/cinema/router.dart
- lib/drawer/class/module.dart
- lib/drawer/ui/module.dart
- lib/event/router.dart
- lib/home/router.dart
- lib/loan/router.dart
- lib/settings/ui/pages/modules_page/modules_page.dart
- lib/tombola/router.dart
- lib/vote/router.dart
- pubspec.lock
- pubspec.yaml
Goal of this PR : 
Enable module to have custom icons as svg as well as regular HeroIcons
Images (if the PR changes the front) :
| Desktop - Mobile |
| ----------- |
|  ![image](https://github.com/aeecleclair/Titan/assets/34400034/b77d9f44-791e-4df3-b9d9-76147eb1daf7) |
| ![image](https://github.com/aeecleclair/Titan/assets/34400034/9af79aa1-c687-4d0e-8637-4901f039adda) |
When selected
- Merge this PR before EloCaps, because it will required svg support
> Using either and svgPicture to specify module icon

- lib/auth/providers/openid_provider.dart
- lib/auth/repository/openid_repository.dart
This bug occurs when you close the logging popup window.
The arrow in the login button of the app stays in the loading state.
This happens because closing the window doesn't change the state of the isLoading provider, which still in loading.
This bug is fixed by watching the state of the popup, and changing the provider state to data if it still in loading, to prevent changing the state when the window is closed because the user logged in.
> Fix: Resetting the loading arrow when the loading popup is closed without logging in

- lib/drawer/ui/quit_dialog.dart
- lib/tools/ui/dialog.dart
Goal of this PR :  Fix a bug that was preventing the log out dialog to close.
This bug had two causes :
- The dialog was not on the routing system,and the rerouting was already handled by the auth provider through providers that depends on it.
- The context was the app one, instead of the QR one, which make the display to be supported by any of the navigator
> Change the way to handle closing dialog

- lib/centralisation/providers/favorites_providers.dart
- lib/centralisation/ui/pages/main_page.dart
Goal of this PR : Allow to reorder favorite modules in Centralisation
- Solve https://github.com/aeecleclair/Titan/issues/113
> Reorder-Centralisation-favorite-modules

- lib/main.dart
Goal of this PR : When an Android user is on the drawer and goes back, he app will be closed
- Answer to https://github.com/aeecleclair/Titan/issues/122
> Exiting app when going back on drawer

- lib/booking/ui/booking_card.dart
- lib/booking/ui/pages/main_page/main_page.dart
- Fix booking card size when information circle is pressed
- Changed the booking card position (the card with the futher sarting date is now appearing first)
> Fix booking card size + booking cards position

- lib/auth/providers/openid_provider.dart
This PR make redirect_uri static for Titan Web.
Even if it's different from localhost, authentication still work in debug mode as Titan is able to catch the auth token regardless of the redirect_uri. This allows compatibility with redirect_uri allowed from Hyperion (see aeecleclair/Hyperion#212)
> Fix redirectUri for web

- .github/workflows/checklabels.yml
preventing PR labeled with Don't Merge or Waiting Backend from being merged
> Add a check labels workflow

- lib/advert/ui/pages/form_page/add_edit_advert_page.dart
> fix: using advert date when editing

- lib/cinema/ui/pages/session_pages/add_edit_session.dart
Goal of this PR : Solves https://github.com/aeecleclair/Titan/issues/232
> fix: removing wrong image bytes retrieval

- lib/settings/ui/pages/edit_user_page/edit_user_page.dart
If promo is null, as there is no possibility to edit it, there is no point in showing it on edit user page
Close #272 
Editing user while Promo is null :
> fix:do not show promo text while promo is null

- pubspec.yaml
Fix a bug where you would not be able to click on an appointment after the package upgrade
> Fix(Booking): downgrade syncfusion_flutter_calendar to previous version

- .env.template
- .github/workflows/release-mobile.yml
- .github/workflows/release-web.yml
- android/app/build.gradle
- lib/admin/router.dart
- lib/advert/router.dart
- lib/amap/router.dart
- lib/booking/router.dart
- lib/centralisation/router.dart
- lib/cinema/router.dart
- lib/event/router.dart
- lib/home/router.dart
- lib/loan/router.dart
- lib/main.dart
- lib/raffle/router.dart
- lib/router.dart
- lib/settings/router.dart
- lib/tools/functions.dart
- lib/tools/plausible.dart
- lib/tools/plausible/plausible.dart
- lib/tools/plausible/plausible_observer.dart
- lib/vote/router.dart
- pubspec.lock
- pubspec.yaml
The goal of this PR is to measure the number of visits on each module thanks to Plausible.
Not tested on iOS.
> Add Plausible to MyECL

- lib/amap/class/order.dart
- lib/amap/tools/constants.dart
- lib/amap/tools/functions.dart
- lib/amap/ui/components/order_ui.dart
- lib/amap/ui/pages/main_page/collection_slot_selector.dart
- test/amap/amap_test.dart
> Fix(Amap) Use constants for slots

- .gitignore
We should remove `pubspec.lock` from `.gitignore` as the file is tracked by git and this is what should be done (https://dart.dev/guides/libraries/private-files#pubspec-lock)
> Remove pubspec.lock from .gitignore

- lib/settings/router.dart
- lib/settings/ui/pages/main_page/main_page.dart
- lib/tools/logs/logger.dart
As it is not possible to use file storage on web browsers, logs may also be disabled for MyECL Web
> Fix(settings): disable logs for web

- lib/tools/providers/map_provider.dart
Fix an error that could happen while editing a mapNotifier through AutoLoaderChild
```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to use MemberPicturesNotifier after `dispose` was called.
E/flutter (14770): 
E/flutter (14770): Consider checking `mounted`.
E/flutter (14770): 
E/flutter (14770): #0      StateNotifier._debugIsMounted.<anonymous closure> (package:state_notifier/state_notifier.dart:175:9)
E/flutter (14770): #1      StateNotifier._debugIsMounted (package:state_notifier/state_notifier.dart:182:6)
E/flutter (14770): #2      StateNotifier.state (package:state_notifier/state_notifier.dart:197:12)
E/flutter (14770): #3      MapNotifier.setTData (package:myecl/tools/providers/map_provider.dart:74:12)
E/flutter (14770): #4 …
```
> Fix: autoLoad/autoLoadList

- android/app/src/main/AndroidManifest.xml
- lib/main.dart
close #307 
Reproduce deprecated WillPopScope behavior with PopScope
https://docs.flutter.dev/release/breaking-changes/android-predictive-back#migrating-from-willpopscope-to-popscope
> Fix: use PopScope instead of deprecated WillPopScope

- lib/loan/class/loan.dart
- lib/loan/tools/constants.dart
- lib/loan/ui/pages/admin_page/loan_card.dart
- lib/loan/ui/pages/admin_page/loan_history.dart
- test/loan/loan_test.dart
Closes #252.
Requires aeecleclair/Hyperion#352
> Change loan history order

- .github/workflows/build.yml
- .github/workflows/release-mobile.yml
- README.md
- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/profile/AndroidManifest.xml
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- lib/auth/providers/openid_provider.dart
The goal of this PR is to allow a connection to a local Hyperion database in debug mode.
I also upgraded gradle scripts in this PR.
> Allow http connection in debug mode and upgrade gradle script

- lib/phonebook/providers/association_member_list_provider.dart
- lib/phonebook/providers/association_provider.dart
- lib/phonebook/repositories/association_repository.dart
- lib/phonebook/ui/pages/admin_page/admin_page.dart
- lib/phonebook/ui/pages/association_creation_page/association_creation_page.dart
- lib/phonebook/ui/pages/association_editor_page/association_editor_page.dart
- lib/phonebook/ui/pages/association_page/association_page.dart
- lib/phonebook/ui/pages/main_page/main_page.dart
- lib/phonebook/ui/pages/member_detail_page/member_detail_page.dart
I removed the endpoint GET phonebook/associations/{association_id} because it doesn't exist in Hyperion.
It was causing issues with refresher widget on some pages of the module.
> Fix refresher issue

- lib/amap/ui/pages/admin_page/user_cash_ui.dart
- lib/flappybird/ui/flappybird_template.dart
- lib/tools/ui/widgets/text_entry.dart
Goal of this PR : Allow amap admin to add negative prices
> feat: allowing amap admin to add negative price

- web/index.html
When running the web version, we are getting warning `Warning: In index.html:157: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.`
This pull request makes use of the {{flutter_service_worker_version}}" template token
> Use flutter service worker version template

- lib/tools/providers/should_notify_provider.dart
Prevent the Email modification popup to be display until the user data are loaded, preventing it to flash while loading the main page
> fix: handling loading case as no data case

- pubspec.yaml
> [!IMPORTANT]
>  We really need to release new versions **soon**, as we have not for several months and there's some time needed to test in alpha before prod.
This goes hand in hand with the **major version bump** [for Hyperion](../../Hyperion/pull/642).
Both PRs are ready, and _seemingly_ waiting for some more **breaking changes** to be merged, including (by likelihood):
> Bump version 1.0.0

- lib/paiement/providers/selected_store_provider.dart
Feedback: several people scanned several times for the wrong store because the default one was always the same.
Now we put in the storage the ID of the last store selected by the user, so that when s/he comes back on MyECL during an event on behalf of one club, the virtual money goes the right store.
> Remember what store the user selected last
